name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Get dependencies
      run: |
        sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

    - name: Build
      env:
       ID: ${{ secrets.REDDIT_CLIENT }}
       SECRET: ${{ secrets.REDDIT_SECRET }}
      run: go build -ldflags "-X main.client=$ID" "-X main.clientsecret=$SECRET" -v ./... 
